exports.up = async (sql) => {
  await sql`CREATE TABLE games (
   id integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
	 room_id integer REFERENCES rooms(id) ON DELETE CASCADE,
	 canvas_data varchar(300),
	 active_player_id varchar(50),
	 start_game_endTime DATE,
	 firstPlayer varchar(40),
	 word varchar(40),
	 rounds int
  )`;
};
exports.down = async (sql) => {
  await sql`
	DROP TABLE games `;
};
