exports.up = async (sql) => {
  await sql`CREATE TABLE games (
   id integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
	 room_id integer REFERENCES rooms(id) ON DELETE CASCADE,
	 canvas_data varchar(200) NOT NULL,
	 active_player_id boolean NOT NULL,
	 start_game DATE
  )`;
};
exports.down = async (sql) => {
  await sql`
	DROP TABLE games `;
};
