exports.up = async (sql) => {
  await sql`CREATE TABLE users (
    id integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
		next_users_id varchar(40)
  )`;
};
exports.down = async (sql) => {
  await sql`
	DROP TABLE users`;
};
