import Head from 'next/head';
import React, { useCallback, useEffect, useRef, useState } from 'react';
import { io } from 'socket.io-client';
import styled from 'styled-components';

const Main = styled.div`
  background-color: red;
`;
const socket = io('http://localhost:8000', {
  transports: ['websocket'],
});
export default function Home() {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Main>chat</Main>
    </div>
  );
}
